console.log(2 > 1)
console.log(2 < 1)
console.log(2 >= 1)
console.log(2 <= 1)
console.log(2 == 1)
console.log(2 != 1)
console.log(2 == "2")
console.log(2 === "2")
console.log(2 !== "2")  

//avoid this converssion of string to number and number to string, because it can lead to unexpected results. Always use explicit conversion methods like Number() or String() for clarity and to avoid bugs.
console.log(null > 0)
console.log(null >= 0)
console.log(null == 0)
console.log(null < 0)
console.log(null <= 0)  

console.log(undefined > 0)
console.log(undefined < 0)
console.log(undefined == 0)
console.log(undefined >= 0)
console.log(undefined <= 0) 